### ISSUE TITLE
后台管理-》文章管理-》点开文件标题进去时报异常了

### ISSUE THREAD

**Issue by inchonline** [osroom/osroom#11]
[2018-12-23 12:00:52,089] ERROR in app: Exception on /api/post [GET]
Traceback (most recent call last):
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/myuu/www/osroom/apps/modules/post/apis/post.py", line 42, in api_post
    data = get_post()
  File "/home/myuu/www/osroom/apps/modules/post/process/post.py", line 18, in get_post
    data = get_post_pr(post_id=post_id)
  File "/home/myuu/www/osroom/apps/modules/post/process/post_process.py", line 210, in get_post_pr
    query_conditions["_id"] = ObjectId(post_id)
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/home/myuu/venv/venv_osr/lib/python3.6/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '5' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

**Comment by HiWoo** [comment]
上一次不小心改错代码导致的，马上修复！

**Comment by HiWoo** [comment]
上一次不小心改错代码导致的，马上修复！
