### ISSUE TITLE
首次启动时，系统提示NameError: name 'mdb_sys' is not defined

### ISSUE THREAD

**Issue by mynameisshiy** [osroom/osroom#15]
Traceback (most recent call last):
  File "start.py", line 43, in <module>
    init_datas(mdb_user=mdb_user, mdb_web=mdb_web, mdb_sys=mdb_sys)
  File "/home/osroom/apps/core/utils/update_db_collection.py", line 95, in init_datas
    init_default_datas()
  File "/home/osroom/apps/core/utils/update_db_collection.py", line 114, in init_default_datas
    if mdb_sys.dbs["theme_display_setting"].find_one(
NameError: name 'mdb_sys' is not defined

跟踪代码后，发现/home/osroom/apps/core/utils/update_db_collection.py中的第98行函数init_default_datas里面使用到了mdb_sys、mdb_web变量，但是使用前并未赋值，所以报错。
调整该函数需要传入mdb_sys、mdb_web、mdb_user后，在调用时传入，程序成功启动。
请看下该问题是否存在，是不是我使用错误了。

**Comment by HiWoo** [comment]
@mynameisshiy 是BUG，应该是某次整理代码的时候，手误把init_datas需要的参数删了。谢谢！已修复

**Comment by HiWoo** [comment]
@mynameisshiy 是BUG，应该是某次整理代码的时候，手误 把init_default_datas需要的参数删了。谢谢！已修复
