### ISSUE TITLE
mongo 好像写不进去

### ISSUE THREAD

**Issue by sindre97** [osroom/osroom#34]
* Update and sync config.py
Traceback (most recent call last):
  File "start.py", line 32, in <module>
    init_before_startup(is_debug=is_debug, csrf_enabled=csrf_enabled)
  File "/home/sindre/osroom/apps/init_before_startup.py", line 74, in init_before_startup
    r = update_config_file(mdbs=mdbs)
  File "/home/sindre/osroom/apps/core/flask/update_config_file.py", line 27, in update_config_file
    version_info = mdbs["sys"].db.sys_config.find_one(
AttributeError: 'Conlections' object has no attribute 'sys_config'

**Comment by HiWoo** [comment]
修复中，v2.2有些问题

**Comment by HiWoo** [comment]
修复了一下，我这边测试已没有这个问题了。目前正在开发v3,将会修复一些其他问题。
